name: Validate on PR

on:
  pull_request

jobs:
  install-dependencies-and-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - uses: actions/cache@v2
        id: node-modules
        with:
          path: ./node_modules
          key: node_modules-${{ hashFiles('./yarn.lock') }}
          restore-keys: node_modules-${{ hashFiles('./yarn.lock') }}
      - run: yarn install
      - name: Yarn lint
        run: yarn lint
      - name: Unit tests
        run: yarn test
      - name: Yarn build
        run: yarn build
        env:
          NODE_ENV: production
      - name: Build Image
        run: |
          docker build -t andreluizmelo/front-store-app:${{ github.sha }} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'andreluizmelo/front-store-app:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'